/**
 * Source of the stdio MCP server that the spawned `claude` process loads via
 * `--mcp-config`. It is written to disk at runtime (see ToolHost.writeBridge)
 * rather than shipped as a resource file, so packaging needs no extra plumbing.
 *
 * The script is deliberately dependency-free ESM and speaks only two things:
 * newline-delimited JSON-RPC on stdio, and the app's localhost JSON API.
 *
 * It is authored without template literals so it can live inside one here.
 */
export const BRIDGE_SCRIPT_SOURCE = `#!/usr/bin/env node
// Generated by Second Brain. Do not edit — rewritten on every launch.
//
// Bridges Claude Code's MCP client to the running app's tool host.

import { createInterface } from 'node:readline'
import { appendFileSync } from 'node:fs'

const BRAIN_URL = process.env.BRAIN_URL
const BRAIN_TOKEN = process.env.BRAIN_TOKEN
const BRAIN_SESSION_ID = process.env.BRAIN_SESSION_ID || null
const BRAIN_LOG = process.env.BRAIN_BRIDGE_LOG || null

// Tools this run's capability tier withholds, by name. The CLI engines are also given
// --disallowedTools, but Codex has no equivalent flag — so without this gate, a read-only Codex
// chat could create and trash notes while its sandbox was dutifully read-only. Enforced here
// rather than only in the app because this is the one place every CLI engine's tool calls pass
// through, and a rule applied at the surface holds only until the next caller.
const BRAIN_DENY = new Set(
  (process.env.BRAIN_DENY || '')
    .split(',')
    .map(function (name) {
      return name.trim()
    })
    .filter(Boolean)
)

// stdout carries protocol frames only. Diagnostics go to stderr, and to a file
// when BRAIN_BRIDGE_LOG is set — the host that spawns this process does not
// always surface a child's stderr, so a log file is the reliable channel.
function debug(message) {
  const line = '[brain-bridge] ' + message
  if (process.env.BRAIN_BRIDGE_DEBUG) process.stderr.write(line + '\\n')
  if (BRAIN_LOG) {
    try {
      appendFileSync(BRAIN_LOG, new Date().toISOString() + ' ' + line + '\\n')
    } catch (err) {
      // never let logging break the transport
    }
  }
}

debug('started pid=' + process.pid + ' url=' + String(BRAIN_URL) + ' session=' + String(BRAIN_SESSION_ID))

function send(payload) {
  process.stdout.write(JSON.stringify(payload) + '\\n')
}

function respond(id, result) {
  send({ jsonrpc: '2.0', id: id, result: result })
}

function respondError(id, code, message) {
  send({ jsonrpc: '2.0', id: id, error: { code: code, message: message } })
}

async function rpc(body) {
  if (!BRAIN_URL || !BRAIN_TOKEN) throw new Error('bridge is not configured')

  const res = await fetch(BRAIN_URL + '/rpc', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: 'Bearer ' + BRAIN_TOKEN
    },
    body: JSON.stringify(Object.assign({ sessionId: BRAIN_SESSION_ID }, body))
  })

  if (!res.ok) throw new Error('tool host returned HTTP ' + res.status)
  return await res.json()
}

let cachedTools = null

async function listTools() {
  if (cachedTools) return cachedTools
  const data = await rpc({ op: 'list' })
  cachedTools = (data.tools || [])
    .filter(function (tool) {
      return !BRAIN_DENY.has(tool.name)
    })
    .map(function (tool) {
      return {
        name: tool.name,
        description: tool.description,
        inputSchema: tool.inputSchema
      }
    })
  return cachedTools
}

async function handle(message) {
  const id = message.id
  const method = message.method

  debug('<- ' + String(method) + ' id=' + String(id))

  // Notifications carry no id and must never be answered.
  const isNotification = id === undefined || id === null

  if (method === 'initialize') {
    const clientVersion =
      message.params && message.params.protocolVersion ? message.params.protocolVersion : '2025-06-18'
    respond(id, {
      // Echo the client's version so we stay compatible as the spec moves.
      protocolVersion: clientVersion,
      capabilities: { tools: { listChanged: false } },
      serverInfo: { name: 'second-brain', version: '0.1.0' }
    })
    return
  }

  if (method === 'notifications/initialized' || method === 'initialized') {
    debug('client initialized')
    return
  }

  if (method === 'ping') {
    if (!isNotification) respond(id, {})
    return
  }

  if (method === 'tools/list') {
    try {
      const tools = await listTools()
      respond(id, { tools: tools })
    } catch (err) {
      respondError(id, -32603, 'could not list tools: ' + String(err && err.message ? err.message : err))
    }
    return
  }

  if (method === 'tools/call') {
    const params = message.params || {}

    // Refused as well as hidden. A model that saw the name in an earlier session, or read it in
    // its instructions, must not get through by asking for it directly.
    if (BRAIN_DENY.has(params.name)) {
      debug('refused ' + String(params.name) + ': withheld at this capability')
      respond(id, {
        content: [
          {
            type: 'text',
            text:
              String(params.name) +
              ' is not available in this conversation: it is read-only. Say what you would change instead.'
          }
        ],
        isError: true
      })
      return
    }

    try {
      const result = await rpc({ op: 'call', name: params.name, args: params.arguments || {} })

      const content = [{ type: 'text', text: String(result.content == null ? '' : result.content) }]

      // Image blocks let a tool hand back a screenshot, which is how the agent
      // sees what it built rather than guessing.
      if (Array.isArray(result.images)) {
        for (const image of result.images) {
          if (!image || !image.data) continue
          content.push({
            type: 'image',
            data: image.data,
            mimeType: image.mimeType || 'image/png'
          })
        }
      }

      respond(id, { content: content, isError: Boolean(result.isError) })
    } catch (err) {
      // Report as a failed tool result rather than a protocol error, so the
      // model sees the message and can react instead of the turn aborting.
      respond(id, {
        content: [
          {
            type: 'text',
            text:
              'Second Brain is unreachable: ' +
              String(err && err.message ? err.message : err) +
              '. The app may have closed.'
          }
        ],
        isError: true
      })
    }
    return
  }

  if (isNotification) {
    debug('ignoring notification ' + method)
    return
  }

  respondError(id, -32601, 'method not found: ' + method)
}

const reader = createInterface({ input: process.stdin, terminal: false })

reader.on('line', function (line) {
  const trimmed = line.trim()
  if (!trimmed) return

  let message
  try {
    message = JSON.parse(trimmed)
  } catch (err) {
    debug('unparseable line: ' + trimmed.slice(0, 200))
    return
  }

  handle(message).catch(function (err) {
    debug('handler threw: ' + String(err && err.stack ? err.stack : err))
    if (message && message.id !== undefined && message.id !== null) {
      respondError(message.id, -32603, String(err && err.message ? err.message : err))
    }
  })
})

reader.on('close', function () {
  process.exit(0)
})

process.on('uncaughtException', function (err) {
  debug('uncaught: ' + String(err && err.stack ? err.stack : err))
})
`
